name: Tzz_Reader
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
  intl: ^0.19.0

  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #字体
  fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: fonts/Roboto-Regular.ttf
    - family: Wenjing
      fonts:
        - asset: fonts/WenJinMinchoP0-Regular.otf
  
  assets:
    - resource/books/
    - resource/data/

