# .github/workflows/deploy.yml

name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main # 或者你的主开发分支

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 授予 GITHUB_TOKEN 写入仓库内容的权限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build Flutter web app
        # 确保这里的 <你的仓库名> 是正确的
        run: flutter build web --release --base-href /Tzz_Reader/ # 假设 Tzz_Reader 是你的仓库名

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web